### ISSUE TITLE
Time for a new umbrella

### ISSUE THREAD

**Issue by kevinbader** [Accenture/reactive-interaction-gateway#102]
EDIT: `:cloud_events` => `:rig_cloud_events`, see #134 

# Time for a new umbrella

This will be fun.

## Problem

For RIG 1.x, there were two ways data could flow: either INBOUND or OUTBOUND. INBOUND meant a webserver and SSE/WebSocket support, and all requests originated from the external network. On the other hand, OUTBOUND meant a different webserver (running on a different port) that exclusively provided RIG's internal API, and connectivity to webservers on the internal network as well as to Kafka and Kinesis brokers. Consequently, it seemed straightforward to build separate OTP apps for this and life was good.

At least until more requirements came along.

Today, the naming is already quite misleading in some cases. For example:

- INBOUND also offers an API to submit OUTBOUND events
- INBOUND offers a way to produce to (internal) Kafka or Kinesis topics, which means that those connections no longer exclusively belong to OUTBOUND. (Also, theoretically an INBOUND request could be set up to produce a message to the OUTBOUND's Kafka topic - O_o)

## A better architecture

With more ways to send and receive stuff to and from RIG, it is more important now to have good abstractions for handling connections to Kafka, Kinesis and similar services in the future. Unfortunately, the current Kafka and Kinesis related code feels scattered around the code base. With features depending on each other it becomes increasingly difficult to add new integrations (Redis, AMQP, etc) to RIG.

The idea is to create a new project layout, modelled around process trees, with clear dependencies and defined behaviors for protocol implementations. The following listing is not exhaustive (especially with respect to features), but represents a rough draft for how we could do it.

#### `:rig_cloud_events`

- `CloudEvent` struct for handling CloudEvents v0.1 and (the current) v0.2

#### `:rig_metrics`

- Initializes Prometheus (the exporter's `setup/0` call only; the /metrics endpoint is exposed by `:rig_control`) - see #96 

#### `:rig_broker`

- `BrokerConnection` behaviour:
  - `subscribe(conn \\ global_conn, topic, cb) :: id`
  - `unsubscribe(id)`
  - `publish(conn \\ global_conn, topic, key, event)`
- in dedicated app to prevent a circular dependency between `:rig_brokers` and `:rig_kafka`/`:rig_kinesis`/etc.

#### `:rig_brokers`

- starts kafka and kinesis supervisors (passes config)
- provides `available_broker_connections() :: [broker connection]`, based on configuration

#### `:rig_kafka`

- implements `BrokerConnection` behaviour
- manages Kafka broker connections

#### `:rig_kinesis`

- implements `BrokerConnection` behaviour
- manages Kinesis client Java application

#### `:rig_sessions`

- session management
- manages blacklist (+ synchronization)

#### `:rig_event_hub`

- event filters and subscription handling
- forwards events to filters:
  `for broker <- available_broker_connections(), do: broker.subscribe(event_topic, forward_event_to_filter)`
- forwards events to HTTP endpoint (firehose):
  `for broker <- available_broker_connections(), do: broker.subscribe(event_topic, forward_event_to_webservice)`
- phoenix endpoint with
  - route for submitting an event
  - route for SSE connection (create connection, subscribe topic)
  - route for WS connection (create connection, subscribe topic)
  - route for topic subscription for existing connections

#### `:rig_proxy`

- phoenix endpoint that accepts external HTTP requests
- subscribes to async responses:
  `for broker <- available_broker_connections(), do: broker.subscribe(response_topic, forward_response_to_conn_proc)`
- for http target type, the request is forwarded using an HTTP client
- for other target types, TARGET.publish is invoked
  - the topic is static (configuration)
  - the key is the session ID (jti) or request id
- if async_response is set, a correlation id is added to the request and the
  connection is left open, waiting for the response (the response can come via any
  of the available broker connections).

#### `:rig_control`

- phoenix endpoint with
  - route for proxy configuration CRUD
  - route for querying sessions
  - route for blacklisting sessions
  - route for Prometheus metrics (future feature)

### Dependencies among OTP apps

![otp_app_deps](https://user-images.githubusercontent.com/1306829/50721953-40500380-10c8-11e9-94f4-bc8ae63dd728.png)

**Comment by vanillebear** [comment]
@kevinbader: If I understood correctly, the apps (except CloudEvents) are still to be grouped into one single :rig-umbrella application, right? Maybe you could add that to the graphic. 

Other then that, I think the planned architecture is much more understandable compared to the current setup
