### ISSUE TITLE
Revisit (rewrite or remove) rate limiting

### ISSUE THREAD

**Issue by kevinbader** [Accenture/reactive-interaction-gateway#144]
Currently, the code around rate limiting is basically dead: inactive by default, with config values in the ops-guide marked as deprecated. We need to decide whether we need this feature. If we do, we need to check whether we can re-use existing code; otherwise, we should get rid of it.

**Comment by jakobwgnr** [comment]
As discussed with @kevinbader and @mmacai the Rate limiting won't be used anymore and should be removed from the code.
