### ISSUE TITLE
inter-service communication 

### ISSUE THREAD

**Issue by chengoldbond1** [Accenture/reactive-interaction-gateway#15]
can you explain how can I use it as an intercommunication between the services?

**Comment by kevinbader** [comment]
RIG provides a way to send messages to your frontends through SSE or WebSockets. For exchanging messages between your backend services, I'd suggest using either direct calls (REST/RPC/...) or a message broker like Kafka. Does that help?

**Comment by chengoldbond1** [comment]
thanks!
