### ISSUE TITLE
Unclear/Broken Blacklist implementation

### ISSUE THREAD

**Issue by jakobwgnr** [Accenture/reactive-interaction-gateway#156]
As discovered during analysis for #96 it seems like the implementation of the "Blacklist" feature is unclear or even broken.

It seems like the module `RigAuth.Blacklist` is not being used anywhere.

Details should be analysed with that issue.

**Comment by kevinbader** [comment]
Just to clarify, the feature is definitely **not** broken. However, there seems to be some dead code leftover after the feature has been refactored a few month back.

**Comment by mmacai** [comment]
As a side note, update of documentation with Blacklist functionality should be part of this.
