### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by jakobwgnr** [Accenture/reactive-interaction-gateway#169]
## Summary and context

As identified during PR #166 the two following examples are not working right now.
´examples/sse-demo-jwt-extractors.html´
´examples/sse-demo-jwt-extractors-conn.html´

## How to reproduce

Try out the examples

## Versions (please complete the following information):**

 - Host OS: Windows 
 - Frontend chrome, safari
 - RIG version as shown on startup 2.1.0

**Comment by mmacai** [comment]
I'll check it.
