### ISSUE TITLE
Tutorial Improvements

### ISSUE THREAD

**Issue by jakobwgnr** [Accenture/reactive-interaction-gateway#173]
I was just going through the documentation and I think we could slightly improve the tutorial. 

Following things I could think of:
- Describing the use case we are showing
- Describing the artifacts we are using/mocking in this tutorial (RIG, the frontend, the backend)
- Clearly mention for each step which artifact we're working on right now
- Remove step 6 from the workflow as it actually doesn't fit there. It should be mentioned that this is how you would implement above's steps in a JS frontend?

What do you guys think? @kevinbader @mmacai

**Comment by kevinbader** [comment]
Sounds very reasonable to me. Can you throw a draft together and do a PR? Then we can discuss on the individual parts.

**Comment by jakobwgnr** [comment]
sure thing!
