### ISSUE TITLE
Fix subscriptions endpoint for cluster setup

### ISSUE THREAD

**Issue by chadmott** [Accenture/reactive-interaction-gateway#194]
## Summary and context

RIG, with scaling configs as described [here](https://github.com/Accenture/reactive-interaction-gateway/blob/25f1a8f77bcd887f1ec43b7aae2641383d285426/docs/scaling.md) produces the following error:

```
14:28:22.120 [info]  Sent 500 in 769µs
request_id=2ma26edlpobqut1it80000d1 application=plug module=Plug.Logger function=call/2 file=lib/plug/logger.ex line=34 pid=<0.2748.0>
:gen_event handler Logger.Backends.Console installed in Logger terminating
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {%ArgumentError{message: "argument error"}, [{:erlang, :is_process_alive, [#PID<38654.6177.0>], []}, {RigInboundGatewayWeb.V1.SubscriptionController, :connection_alive!, 1, [file: 'lib/rig_inbound_gateway_web/v1/subscription_controller.ex', line: 122]}, {RigInboundGatewayWeb.V1.SubscriptionController, :set_subscriptions, 2, [file: 'lib/rig_inbound_gateway_web/v1/subscription_controller.ex', line: 74]}, {RigInboundGatewayWeb.V1.SubscriptionController, :action, 2, [file: 'lib/rig_inbound_gateway_web/v1/subscription_controller.ex', line: 1]}, {RigInboundGatewayWeb.V1.SubscriptionController, :phoenix_controller_pipeline, 2, [file: 'lib/rig_inbound_gateway_web/v1/subscription_controller.ex', line: 1]}, {RigInboundGatewayWeb.Endpoint, :instrument, 4, [file: 'lib/rig_inbound_gateway_web/endpoint.ex', line: 1]}, {Phoenix.Router, :__call__, 1, [file: 'lib/phoenix/router.ex', line: 275]}, {RigInboundGatewayWeb.Endpoint, :plug_builder_call, 2, [file: 'lib/rig_inbound_gateway_web/endpoint.ex', line: 1]}]}. This protocol is implemented for: Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Rig.Subscription, Time, URI, Version, Version.Requirement
        (elixir) /usr/local/src/elixir/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) /usr/local/src/elixir/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
        (logger) lib/logger/formatter.ex:166: anonymous fn/1 in Logger.Formatter.output/5
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (logger) lib/logger/formatter.ex:152: anonymous fn/6 in Logger.Formatter.format/5
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (logger) lib/logger/formatter.ex:151: Logger.Formatter.format/5
```
if I scale back to 1, things work as expected and my e2e tests pass

I do see the RIG acknowledgement of itself
```
13:06:41.615 [debug] [Peerage 1.0.3][ Elixir.Peerage.Via.Dns] Discovery every 5s.
     NAME                RESULT OF ATTEMPT
     rig@10.0.94.143     true
     LIVE NODES
     rig@10.0.94.143 (self)
     rig@10.0.94.88
     rig@10.0.94.116
```

and I do see it rebalance across kafka. I also see the requests come in across the three instances.  

## How to reproduce

Run the rig as described [here](https://github.com/Accenture/reactive-interaction-gateway/blob/25f1a8f77bcd887f1ec43b7aae2641383d285426/docs/scaling.md) using the master branch. 

> Describe whether you use Docker or not, the environment variables you set and the config files you use.

- Kubernetes/Docker
- Confluent Kafka 5.1.2

## Versions (please complete the following information):**

 - Host OS: whatever AKS runs K8s on, we use the RIG docker container
 - Frontend node "supertest" framework, but it also appears we cannot subscribe using normal browsers (chrome latest)
 - RIG version as shown on startup Master

**Comment by mmacai** [comment]
Tested and can confirm. Weird thing is that, when I open my UI for the first time I get the same error. When I refresh the browser (so it does SSE calls again), everything works.

**Comment by mmacai** [comment]
Tested it one more time and it's more of a random behaviour, seems like RIG is trying to use PID on wrong node (from time to time it hits correct node and subscription is fine).
