### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by kevinbader** [Accenture/reactive-interaction-gateway#2]
Some ideas:
- How fast can messages be routed when scaling out (with multiple connections per user to different RIG instances)?
- How many concurrent downstream connections (SSE, WebSockets) can be handled?
- How big is the typical request latency for proxied requests?
- How large can the blacklist grow before performance (?) degrades?

**Comment by mmacai** [comment]
First round done internally, second iteration will come after next release.
