### ISSUE TITLE
Documentation searching

### ISSUE THREAD

**Issue by mmacai** [Accenture/reactive-interaction-gateway#200]
We miss search capability in docs, Docusaurus provides such ability https://docusaurus.io/docs/en/search. Should be way easier to find certain piece of content than clicking around.

**Comment by pavestru** [comment]
Docusaurus supports Algolia. In order for Algolia to crawl and index the docs, you need to [ask them](https://community.algolia.com/docsearch/#join-docsearch-program). It's free. Then you add the search bar to Docusaurus. Can I do it?

**Comment by kevinbader** [comment]
Thanks for pointing that out! I didn't know it'd be so easy :) I've already filled out the form - it'll take a few days for them to process it.
