### ISSUE TITLE
can PROXY_KAFKA_RESPONSE_TOPICS and KAFKA_SOURCE_TOPICS be the same?

### ISSUE THREAD

**Issue by chadmott** [Accenture/reactive-interaction-gateway#206]
With the proxy config like the below:

```
"endpoints": [
          {
            "id": "something",
            "path": "/something",
            "method": "POST",
            "secured": false,
            "target": "http",
            "response_from": "kafka"
          }
]
```

I  would like to use the _same_ topic for both streaming events and RESTful response, but if I set `PROXY_KAFKA_RESPONSE_TOPICS` to `rig` and `KAFKA_SOURCE_TOPICS` to `rig`, i do not get the response over HTTP (it times out). 
if I change `PROXY_KAFKA_RESPONSE_TOPICS` to something else, or take it out to use the default `rig-proxy-response` it works (on Kafka, both topics are identical here... I am publishing the appropriate payload on both topics)

Not opening as a bug b/c I'm sure it is working as intended, but could we discuss making it possible to just have the one topic?

**Comment by kevinbader** [comment]
Forwarding events and forwarding replies are two different things/features that require different validations (as can be seen [here](https://github.com/Accenture/reactive-interaction-gateway/blob/master/apps/rig/lib/rig/event_stream/kafka_to_filter.ex#L17) and [here](https://github.com/Accenture/reactive-interaction-gateway/blob/master/apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/kafka.ex#L39)), so makes sense to keep them separated. Also, using the same topic means processing each message at least twice.

Nevertheless, I've created a PR for this (#207), so if you really want you'll be able to :)
