### ISSUE TITLE
API proxy file upload

### ISSUE THREAD

**Issue by mmacai** [Accenture/reactive-interaction-gateway#219]
## Summary and context

Currently we do support file upload via `multipart`, but only for `POST` method and using non-standard property `qqfile` - used e.g. by this library https://docs.fineuploader.com/branch/master/api/qq.html.

What I propose is to support additional HTTP methods -- at least `PUT` and convert `qqfile` property naming to regular `file` (or keep current `qqfile` format and support also `file`).

 - Host OS: Mac
 - RIG version 2.1.1 [rig@127.0.0.1, ERTS 10.2.2, OTP 21]]

**Comment by kevinbader** [comment]
as discussed in the call last week, I've changed this in #209:

https://github.com/Accenture/reactive-interaction-gateway/blob/73238378e43c5ce701cb3c632a88fc7a71da617b/apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex#L68

With this change, the body is forwarded verbatim, which means RIG will gain support for any mime type, also for uploading/passing-on files.

**Comment by mmacai** [comment]
> as discussed in the call last week, I've changed this in #209:
> 
> https://github.com/Accenture/reactive-interaction-gateway/blob/73238378e43c5ce701cb3c632a88fc7a71da617b/apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex#L68
> 
> With this change, the body is forwarded verbatim, which means RIG will gain support for any mime type, also for uploading/passing-on files.

Thought so, but wasn't sure. We can check and close this afterwards (if solved).

**Comment by mmacai** [comment]
Resolved by #209
