### ISSUE TITLE
Support HTTP response code with the API's /responses endpoint

### ISSUE THREAD

**Issue by kevinbader** [Accenture/reactive-interaction-gateway#221]
The `/responses` endpoint, which can be used to asynchronously submit responses to incoming HTTP requests, currently doesn't support HTTP response codes. In other words, it's currently not possible to answer such a request with "401 Not authorized", for example.

The reason for this is that we mistakingly expect responses to be sent as CloudEvents (this is also the case for reading responses from Kafka!). Indeed, a response is a _message_ rather than an _event_ and there's no reason at all to expect it to conform to the CloudEvents standard. In fact, RIG doesn't interpret it in any way, so there's no need to put any constraints on the payload format.

To address this I propose the following changes.

# POST API: /v1/responses

Two modes are supported: binary (preferred) and structured.

Since the endpoint hasn't been included in any release so far, we should be able to make the change without caring about backwards compatibility. We should note down how to migrate any early-adopter code in the Changelog, however.

## Binary Mode

The HTTP header contains prefixed meta data:

```plaintext
rig-correlation: the correlation ID as added by RIG to the forwarded request
rig-response-code: 200
```

The body contains the payload in the encoding specified by the "content-type" header:

```plaintext
in binary format; RIG forwards this as-is
```

## Structured Mode

The header is not used, except for the content-type, which must be "application/json".

Body:

```plaintext
{
  "correlation": "the correlation ID as added by RIG to the forwarded request",
  "response-code": 200,
  "content-type": "text/plain",
  "content": "in whatever encoding is specified in content-type + base64; RIG base64-decodes this string and forward this as the response body with the content-type set to what's specified in this body"
}
```

# Reading the response from Kafka topic

Should work the same way. ~~Kafka headers become a requirement.~~ With support for both the binary and the structured transport modes, using Kafka headers is preferred but not required.

To handle the breaking change, we have two options:

1. Deprecate the old way and use a new topic for responses that follow the new format. Remove support for the deprecated topic/format with 3.0.
1. Also deprecate the old way, but support it alongside the new format using the same topic. The code could distinguish the request formats by looking for `rig-correlation` in the header.

# Reading the response from Kinesis

Kinesis doesn't support headers, so Kinesis only supports the structured transport mode as described above.

## Why is binary mode preferred?

Cause structured mode requires binary payloads to be encoded (e.g. using base 64) in order for it to be sent as a string that is valid in JSON terms. This takes up CPU and makes messages larger.

# References

https://github.com/Accenture/reactive-interaction-gateway/blob/master/apps/rig_api/lib/rig_api/controllers/responses_controller.ex

**Comment by chadmott** [comment]
So I really like the notion of keeping emergent behavior of the rig very similar regardless if the endpoint is `kafka` or `http_async`... this allows us to publish messages to kafka _or_ post to the endpoint where appropriate (when I cannot publish certain data, like PII, to kafka) and the UI doesnlt know the difference

One comment that I would make, is why would kafka message headers be required? This is problematic for those who use `librdkafka` and its related projects (like `node-rdkafka`) that do not currently support headers. Could we not add the response code to the same `rig` object in the cloud event? so like:

```
rig: {
correlation: <guid>
responseCode?: 401 // if not set, send 200
}

```

**Comment by chadmott** [comment]
ooops...looks like header support coming soon to node-rdkafka as [this](https://github.com/Blizzard/node-rdkafka/pull/579) was just merged 17 hours ago...

nevertheless, I think it would be cool if we could implement something like my prior comment for those who are on older versions

**Comment by kevinbader** [comment]
@chadmott oh I didn't realize support for Kafka headers is not widespread already.

> Could we not add the response code to the same rig object in the cloud event?

As layed out above, the response message is _not_ a CloudEvent ;) Okay, then we'll have to go for a structured mode similar to how it's done in the CloudEvents spec. Let me update the proposal..
