### ISSUE TITLE
Support AWS Kinesis

### ISSUE THREAD

**Issue by kevinbader** [Accenture/reactive-interaction-gateway#27]

**Comment by thomaswmanion** [comment]
It would be great if this was a plugin rather than a feature. Otherwise you're going to have download the entire RIG package for native v. AWS v. Azure adapters.

**Comment by kevinbader** [comment]
@thomaswmanion The source code is not actually a plugin, but the dependency on Java is only there if you need it. We're preparing a dedicated Docker image, so the current image remains the same size.
