### ISSUE TITLE
Delete api does not returns success or failure.. 

### ISSUE THREAD

**Issue by laadpooja** [Accenture/reactive-interaction-gateway#272]
http://localhost:4010/v1/apis/apiId

This API does not return success or failure. however, it successfully deletes the Gateway. Which cause error detection in the catch block of try-catch.

**Comment by kevinbader** [comment]
@laadpooja Thanks for the report! @mmacai can you please take a look at this?

**Comment by mmacai** [comment]
Sure, I'll check.

**Comment by mmacai** [comment]
Can confirm, I'll investigate and fix.
