### ISSUE TITLE
Improve validation for reverse proxy configuration

### ISSUE THREAD

**Issue by kevinbader** [Accenture/reactive-interaction-gateway#277]
The reverse proxy configuration should be validated
- when loading it from a configuration file / environment variable,
- when using the API.

For example, when creating a route with target `kinesis` without a target topic, and the variable `PROXY_KINESIS_REQUEST_STREAM` is not set, loading the configuration should fail. Currently, the configuration will be applied but clients will see an error once they try to use the route.

If an error is encountered:
- If the configuration passed on startup contains an error, RIG should refuse to start.
- If the configuration passed to RIG's API contains as error, RIG should respond with an 400 Bad Request status code.

**Comment by mmacai** [comment]
@kevinbader any opinion on something like this https://github.com/CargoSense/vex?

**Comment by kevinbader** [comment]
@mmacai looks cool! I like that it makes it easy to retrieve a list of all errors that occurred during validation - something that's a bit cumbersome when done manually.
