### ISSUE TITLE
Support for OpenTracing

### ISSUE THREAD

**Issue by kevinbader** [Accenture/reactive-interaction-gateway#281]
We'd like RIG to be visible to distributed tracing using the [OpenTracing API](https://opentracing.io/). While it may make sense to communicate some internal events, the first step should be to enable basic tracing of requests through RIG:

- The reverse proxy should respect tracing headers for incoming HTTP requests and add them to forwarded/outgoing HTTP requests.
- When producing events, RIG should add tracing info according to the [CloudEvents distributed tracing extension spec](https://github.com/cloudevents/spec/blob/v1.0/extensions/distributed-tracing.md).

**Comment by petermetz** [comment]
Hey,

You might want to look into OpenTelemetry as well/instead. It is positioned as the next iteration of OpenTracing (same team, not a competing standard as far as I understood from their documentation, but don't quote me on that without checking it yourself :-) )

https://opentelemetry.io/

**Comment by Knappek** [comment]
Thank you @petermetz for pointing that out. We have opentelemetry in mind, but I still see a better and easier integration with opencensus. Opentelemetry ensures backwards compatibility with existing opencensus and opentracing though, so it will be an easy switch to opentelemetry.
