### ISSUE TITLE
Question + Update Docs - Why can't I just use Socket.IO-Server with kafka-node?

### ISSUE THREAD

**Issue by thomaswmanion** [Accenture/reactive-interaction-gateway#30]
If you could add this to the docs too, that would be great.

Why I'm asking is this was what I've seen done previously for this solution and it is more decoupled. Socket.IO-Server with Kafka is likely less performant (I don't know?) and easier to scale, but it'd be great if we could get some numbers on that.

**Comment by kevinbader** [comment]
I'm not sure what you mean... could you please elaborate? Not sure if you're saying that a nodejs, socket.io based server is easier or harder to scale than RIG...

**Comment by mbuhot** [comment]
In the blog post you mention an update initial node implementation: 

> Our first prototype was written in Node.js. The app worked, but scaled very poorly in both directions. 

Some more details on the scaling issues encountered would be helpful.

**Comment by kevinbader** [comment]
I agree, we need some numbers that prove that claim. Indeed, we're currently preparing another round of performance tests to guide upcoming performance optimizations, and also talked about applying the same tests to the Node based implementation. We'll publish the results in another blog post. Thanks for the suggestion!

**Comment by LeDominik** [comment]
We had some discussion around this: `socket.io` has it's own non-standard protocol and we really don't want to rebuild it here. It also serves a very real-time purpose (think live chat) while the RIG is about a reactive architecture where updates naturally flow in.
