### ISSUE TITLE
RIG failed to build on Linux System

### ISSUE THREAD

**Issue by ghost** [Accenture/reactive-interaction-gateway#333]
I built RIG on Ubuntu Focal (20.04) x86_64 machine, which has failed.
Before building RIG, elixir and erlang has been installed as below
~~~
$ wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
$ sudo apt-get update
$ sudo apt-get install esl-erlang
$ sudo apt-get install elixir
~~~
This has installed elixir version 1.10.4 and erlang version 23.0.

After this, I followed below steps for the build
~~~
$ mix deps.get
$ mix phx.server
~~~ 
**_$ mix deps.get_** passed well, but **_$ mix phx.server_** fails with below dependency issue
~~~
==> crc32cer (compile)
 DEPEND crc32cer.d
 ERLC   crc32cer.erl
 APP    crc32cer.app.src
 C      crc32c.c
 C      crc32c_nif.c
 LD     crc32cer.so
/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status
make: *** [erlang.mk:5803: /reactive-interaction-gateway/deps/crc32cer/priv/crc32cer.so] Error 1
ERROR: Command [compile] failed!
==> rig
** (Mix) Could not compile dependency :crc32cer, "/root/.mix/rebar compile skip_deps=true deps_dir="/reactive-interaction-gateway/_build/test/lib"" command failed. You can recompile this dependency with "mix deps.compile crc32cer", update it with "mix deps.update crc32cer" or clean it with "mix deps.clean crc32cer"
~~~

Can you please check what am I doing wrong here? Do I need to install some dependencies?

**Comment by wichpatricke** [comment]
**PS:** The same behaviour has been seen in Ubuntu Bionic (18.04) x86_64 system.

**Comment by Knappek** [comment]
Hi @wichpatricke thanks for reporting this issue. 
Can you please run `mix deps.compile crc32cer`, this will return more information why compiling `crc32cer` fails. If packages are missing, you can also compare with the Dockerfiles of [elixir](https://github.com/c0b/docker-elixir/blob/a8d582c328db5864a4e8e5f869900e3a52265f38/1.10/Dockerfile) and [erlang](https://github.com/erlang/docker-erlang-otp/blob/fcbf78da4197c65d09d3982103016415c26884f9/22/slim/Dockerfile). 
Let me know whether this helps.

**Comment by Knappek** [comment]
Hi @wichpatricke, thanks for reporting this issue. I am able to reproduce it. I'll keep you posted once I solved it.

**Comment by kevinbader** [comment]
Seems our current dependency versions don't compile with OTP 23. I've successfully built the code base using Elixir 1.10.4 compiled with Erlang/OTP 22. I've added #341 as a follow-up. Let me know if you still have build problems also with those versions.
