### ISSUE TITLE
Leaving out `path` in endpoint declaration let RIG fail on startup

### ISSUE THREAD

**Issue by KaWigg** [Accenture/reactive-interaction-gateway#334]
## Summary and context

> Rewriting URLs in API Gateway only works when using regex catch groups, so we need to use `path_regex` instead of `path` when defining the path. Leaving out `path` declaration leads to a validation error on startup.

## How to reproduce

**When I run RIG with this endpoint:**

 ```
{
   "id": "get-entry",
   "path_regex": "/entries/(([\\d\\w])*(-([\\d\\w])*))",
   "path_replacement": "/api/entries/\\1",
   "method": "GET",
   "secured": false
}
```

**..I see the following error and/or log output:**

> module=RigInboundGateway.ApiProxy.Validations [error] Wrong reverse proxy configuration: [{"service-endpoint/get-entry", [{:error, "path", :by, "must be string"}, {:error, "path", :length, "must have a length of at least 1"}]}]

**..but I really expected this:**

> Normal startup because `path_regex` is set instead of `path`. This is also used in your tests and here [Forwarding Requests](https://accenture.github.io/reactive-interaction-gateway/docs/api-gateway.html#url-rewriting) 
OR 
> Allow dynamic parameters introduced by `{dynamic_paramter}` to be used in `path_replacement`, like
```
{
   "id": "get-entry",
   "path": "/entries/{entry_id}",
   "path_replacement": "/api/entries/{entry_id}",
   "method": "GET",
   "secured": false
}
```

## Versions (please complete the following information):**

 - Latest docker image `accenture/reactive-interaction-gateway:latest`
 - Reactive Interaction Gateway 3.0.0-alpha.1 [rig@127.0.0.1, ERTS 10.7.2.3, OTP 22]

**Comment by mmacai** [comment]
@KaWigg Thank you! I'll check it tomorrow through out the day.

**Comment by mmacai** [comment]
@KaWigg can you give this a shot https://github.com/Accenture/reactive-interaction-gateway/pull/335?

Btw, if you don't need auth, you don't have to set `secured` property.
