### ISSUE TITLE
CORS + jwt secured route for http target, no matching clause

### ISSUE THREAD

**Issue by KaWigg** [Accenture/reactive-interaction-gateway#343]
## Summary and context

> If we dont set `"secured": false` explicitly for `OPTIONS` requests to a corresponding secured route, RIG throws a `FunctionClauseError`

## How to reproduce

Using a proxy config with a secured endpoint + a OPTIONS endpoint with `secured` **not** set

```
[
  {
    "id": "service",
    "auth_type": "jwt",
    "auth": {
      "use_header": true,
      "header_name": "Authorization",
      "use_query": false,
      "query_name": ""
    },
    "name": "Service",
    "version_data": {
      "default": {
        "endpoints": [
          {
            "id": "get",
            "path": "/random",
            "method": "GET",
            "secured": true
          }
          ,{
            "id": "get-preflight",
            "method": "OPTIONS",
            "path": "/random",
          }
        ]
      }
    },
    "proxy": {
      "use_env": false,
      "name": "reverse",
      "target_url": "http://service/",
      "port": 4000
    }
  }
]
```

Calling `/random` produces the error

```
Request: OPTIONS /users
** (exit) an exception was raised:
     ** (FunctionClauseError) no function clause matching in RigInboundGateway.ApiProxy.Auth.check/3
```

Reproduced this on latest docker image 'accenture/reactive-interaction-gateway:latest' aswell as actual master
I dont think any other env variables or configs will have an impact on this.

**..but I really expected this:**

Since `"secured": false` is a default for endpoints it should also be a default for `OPTIONS` request because a secured OPTIONS request makes no sense at all. Additionally CORS specification excludes credentials even if they are present.

Setting `"secured": false` manually fixes this. 

## Versions (please complete the following information):**

 - Host OS: Description:	Ubuntu 18.04.5 LTS
                                        Release:	18.04
                                        Codename:	bionic
                                        amd64
 - Frontend, tested in Chrome and Firefox
 - RIG version as shown on startup: Reactive Interaction Gateway 3.0.0.alpha.1 [rig@127.0.0.1, ERTS 10.7.2.1, OTP 22]

**Comment by mmacai** [comment]
@KaWigg Can you please test it with the latest changes from yesterday? Noticed some wrong pattern matching and changed it here https://github.com/Accenture/reactive-interaction-gateway/pull/336/files#diff-cddd2da34a3e28e1a8128cb69d60f6a5a62c23f7a08d0a85758284b98963b5c6. Unless you already have it.

**Comment by KaWigg** [comment]
@mmacai that pr solves this!

**Comment by mmacai** [comment]
@KaWigg Glad to hear that! Closing.
