### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by kevinbader** [Accenture/reactive-interaction-gateway#41]
Logos are important. There are some ideas, perhaps a pictogram of an oil rig, but we're open to creative ideas here

**Comment by aymyers** [comment]
Something like this maybe?

![rig-logo](https://user-images.githubusercontent.com/13636646/36949804-8f10cc26-1faa-11e8-8804-ff5041795002.jpg)

**Comment by kevinbader** [comment]
@aymyers nice, I like it! 🎉🙌 Is it okay to build on it, or which license do you have in mind? Thanks!

**Comment by aymyers** [comment]
You can build on it!
