### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Lavaei** [Accenture/reactive-interaction-gateway#418]
Can anyone answer this question? Is this project still alive? Can I use it in my project?

**Comment by mmacai** [comment]
Hi @Lavaei, I don't think there will be some new features in the near future. However, I would like to do an official 3.0.0 release in the first half of August and from there do some critical bug fixes if time allows.

**Comment by Lavaei** [comment]
Thanks for your reply. Unfortunately I don't know Elixir to contribute to this fantastic project. But I hope someone in the Elixir community helps this project to continue.
