### ISSUE TITLE
Support forwarding inbound HTTP request bodies as events to Kafka & Kinesis

### ISSUE THREAD

**Issue by kevinbader** [Accenture/reactive-interaction-gateway#77]
Right now, HTTP requests are forwarded to backend services. Additionally, other "targets" should be available, like publishing the request to a Kafka or Kinesis topic.

#### Benefits

- If a service is down at the time the request is sent, the request is not lost but can be processed as soon as the service is back up.
- Frontends don't see 504 Gateway Timeout errors, since RIG immediately responds. Assuming the processing service notifies the frontends about picking up the request, the UI just has another state to deal with (e.g., submitted - processing - processed).

**Comment by LeDominik** [comment]
Current plan: Release as Beta-feature in 2.0. We already know that this will be superceded with proper async support in #97, with this initial feature then being the fire & forget mode.

**Comment by mmacai** [comment]
Done in #123
