### ISSUE TITLE
Add support for token type in Authorization header

### ISSUE THREAD

**Issue by lofim** [Accenture/reactive-interaction-gateway#82]
Since we support sending auth (bearer) token via Authorization header we should be compliant with what the rest of the industry is doing.

The [OAuth RFC 7.1](https://tools.ietf.org/html/rfc6749#section-7.1) describes token types.
The current implementation does not consider types at all and will fail to validate the token if the type is set to for example "Bearer".

So the proper form should look like this:
`Authorization : Bearer eyJ0eXAiOiJK`

Instead of this:
`Authorization : eyJ0eXAiOiJK`

AFAIK we only support Bearer token for now.
The question here is what should the gateway do in case it receives a different type.

Either way this should be configurable. We should be able to specify that we expect a type or not.
`AUTH_TOKEN_TYPE=Bearer` sounds reasonable to me.

I'm open to suggestions.

**Comment by kevinbader** [comment]
I'm pretty sure this should be fixed in 2.0.0-beta.2... scoping to 2.0.0-beta.3 to make sure there is a regression test for this
