### ISSUE TITLE
RabbitMQ as Message Broker

### ISSUE THREAD

**Issue by sm-tradeboox** [Accenture/reactive-interaction-gateway#95]
Hello.

Not an issue, but not sure where else to post a query. 

Will RIG work with RabbitMQ as the message broker instead of Kafka? Is this something you've perhaps already done?

Thanks in advance.

**Comment by kevinbader** [comment]
Hi @sm-tradeboox, thanks for the feature request! Indeed, support for RabbitMQ, or AMQP in general, is already on the backlog, see #75. I'll probably start working on this in 2-3 months, but if you're interested in implementing this earlier I'd be happy to provide guidance.

**Comment by kevinbader** [comment]
Closed in favor of #75
