### ISSUE TITLE
Add Concept of "Session"

### ISSUE THREAD

**Issue by chadmott** [Accenture/reactive-interaction-gateway#98]
Current flow, as I understand it, ties RIG activities to the JWT token. This works well in scenarios where I want a "facebook like" experience -- seeing real time updates across devices.

However, I have a use case where I want a single user, with multiple browsers, consuming RIG events, and do _not_ want the messages to propagate to each session. 

Example: User signs in, and wants to work on 2 customer profiles at the same time. Today, when I do things in browser 1, i see events in browser 2, despite being in a totally different application context.

**Comment by kevinbader** [comment]
With #90, using a JWT is no longer mandatory and RIG will no longer group connections together automatically. The change is about supporting a more generic way of event subscriptions and I think it could be used to implement what you're looking for. Please take a look and let me know if this would work for you.

Please note that as a workaround you could simply ignore incoming events that don't match the current application context...

**Comment by kevinbader** [comment]
As discussed, the concept of users and sessions will be reworked for beta.3/beta.4. Multiple browser windows should now be supported with event subscriptions as hinted above, so I'm closing this.
